* 总线

一组能为多个部件分时共享的公共信息传送线路。
分时和共享是总线的两个特点。

分时是指同一时刻只允许有一个部件向总线发送信息，若系统中有多个组部件，那么它们只能分时向总线发送信息。

共享是指总线可以挂接多个部件，它们之间共享信息可以通过总线进行实时共享，多个部件可同时从总线上接收相同的信息。


** 总线特性

1. 电器特性
   
2. 机械特性
   
3. 功能特性
   
4. 时间特性

** 总线分类

1. 片内总线

2. 系统总线
   
   数据总线：双向
   
   地址总线：单向
   
   控制总线

3. I/O 总线

4. 通信总线

** 系统总线的结构

1. 单总线结构

CPU、贮存、I/O 均挂在一组总线上，允许 I/O 设备之间、I/O 设备于主存之间直接交换信息

优点：结构简单、成本低、容易接入新的设备

缺点：带宽低、负载重、没法并发传送

2. 双总线结构

分为贮存总线，用于 CPU、主存和通道之间传送数据；另一条是 I/O 总线，用于在多个外部设备与通道之间传递数据

优点：将低速的 I/O 设备从单总线上分离出来，实现存储器总线和 I/O 总线的分离

缺点：需要额外增加通道等设备

3. 三总线结构

分成三条独立的总线，主存总线、I/O 总线、DMA 总线

主存总线用于在 CPU 和内存之间传送地址、数据和控制信息。

I/O 总线用于在 CPU 和各类外设之间通信

DMA 总线用于在内存和高速外设之间直接传送数据

优点：提高了 I/O 设备的性能，使之更好且更快的响应命令，提高系统吞吐量

缺点：系统工作效率较低

** 总线事务

一个总线周期内发生的一系列活动

1. 请求
2. 仲裁
3. 寻址
4. 传输
5. 释放

*** 同步定时方式

同步定时方式是指系统采用一个统一的时钟信号来协调发送和接收双方的传送定时关系。 若干个时钟产生相等的时间间隔，每个间隔构成一个总线周期。 在一个总线周期中，发送方和接收方可进行一次数据传送。 因为采用统一的时钟，每个部件或设备发送或接收信息都在固定的总线传送周期中，一个总线的传送周期结束，下一个总线传送周期开始。

优点：传送速度快，较高的传输速率，总线控制逻辑简单

缺点：主从设备属于强制性同步，不能及时进行数据通信的有效性检验，可靠性差

同步通信适用于总线长度较短及总线所接部件的存取时间比较接近的系统。

*** 异步定时方式

没有统一的时钟和固定的时间间隔

一般，主设备发出请求交换信息的信号，经过总线送到从设备。
从设备接到主设备的请求后，通过总线对主设备进行回答。

优点：总线周期长度可变，能保证两个工作速度相差很大的部件或设备之间可靠地进行信息交换，自动适应时间的配合。

缺点：比同步控制方式稍复杂，速度比同步方式慢


**** 不互锁

主设备发出请求信号，一段时间后撤销

从设备发出回答信号，一段时间后撤销


**** 半互锁

主设备发出请求信号，等待收到从设备的回答信号后再撤销

从设备发出回答信号，一段时间后撤销

**** 全互锁

主设备发出请求信号，等待收到从设备的回答信号后再撤销

从设备发出回答信号，获知主设备撤销请求信号后载撤销

